name: Deploy to GitHub Pages
# Please
on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Set up Git user
      run: |
        git config --global user.name "EnesAkyuz"
        git config --global user.email "eakyuz0681@gmail.com"

    - name: Install dependencies
      run: yarn install

    - name: Build project
      env:
        VITE_SUPABASE_ANON_KEY: ${{ secrets.VITE_SUPABASE_ANON_KEY }}
        VITE_SUPABASE_URL: ${{ secrets.VITE_SUPABASE_URL }}
      run: yarn build

    - name: Pre-Deploy
      run: yarn predeploy

    - name: Deploy
      run: yarn deploy

    - name: Deploy to GitHub Pages
      uses: peaceiris/actions-gh-pages@v3
      with:
        github_token: ${{ secrets.GITHUB_TOKEN }}
        publish_dir: ./dist  # Replace with your build output directory
